spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/staffdb?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
server:
  port: 8084
